codecov:
  require_ci_to_pass: yes
  allow_coverage_offsets: true
  notify:
      after_n_builds: 2

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  after_n_builds: 2
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
